### ISSUE TITLE
Support More Model?

### ISSUE THREAD

**Issue by sudoskys** [Blarc/ai-commits-intellij-plugin#101]
Openai also has many more models available, would you mind adding them?

Here the list of them all
```python
MODEL = Literal[
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-16k",
    "gpt-3.5-turbo-0613",
    "gpt-3.5-turbo-16k-0613",
    "gpt-4-0613",
    "gpt-4",
    "gpt-4-32k",
    "gpt-4-32k-0613",
     "gpt-3.5-turbo-instruct",
    "gpt-4-0314",
    "gpt-3.5-turbo-0301",
    "gpt-4-32k-0314"
]
```

Sometimes the diff will be very long, I think maybe the `-32k` model can handle it well.

**Comment by Blarc** [comment]
Models are automatically fetched from Open AI API by using the token you provided in plugin settings. You can try clicking the `Refresh` button next to the dropdown to re-fetch models.

**Comment by sudoskys** [comment]
well down
