### ISSUE TITLE
Open AI Configuration is not valid (Unknown)

### ISSUE THREAD

**Issue by briantomasdev** [Blarc/ai-commits-intellij-plugin#102]
Any key won't work

**Comment by nikage** [comment]
> Any key won't work

The same

**Comment by Blarc** [comment]
Did it work previously or have you just started using the plugin?

**Comment by nikage** [comment]
> Did it work previously or have you just started using the plugin?

I've just installed the plugin. I've tried to restart Android Studio a couple of times and generate new token. Nothing helped. But I've just checked again and it started to work now. 

Not sure what was the problem but seems I wasn't the only one. 

Thanks for quick response, btw!
