### ISSUE TITLE
Unable to see additional models

### ISSUE THREAD

**Issue by nano0tech** [Blarc/ai-commits-intellij-plugin#104]
Hello,

I've confirmed my API key works. I can see many more models in my playground, and have confimed the same via Postman (below).

But I don't see any additional models in the model dropdown. Is anyone using a 16k model?

What I've done:

- Added the API Key
- Confirmed it works by generating a commit message
- Restated PHP Storm
- Pressed Refresh

Am I missing something?

_Refresh in action_
![2023-11-09 08 40 13](https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/d08b4827-47cf-4544-8194-94dbe7c79179)

_Model List_
<img width="900" alt="image" src="https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/7dc12340-57b3-41ee-ab75-6d6017928653">

## Model Confirmation

<img width="433" alt="image" src="https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/dcc931f9-6bcb-4bb9-ab77-64888a3db2aa">

<img width="1257" alt="image" src="https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/fcb333f7-29ec-4751-bf1b-d4d459e3aa14">

**Comment by Blarc** [comment]
Hi. Thanks for the detailed issue description. I am using https://github.com/aallam/openai-kotlin for retrieving models. I will release a new version of the plugin that uses the last version of the client and hopefully that fixes your issue.

**Comment by Blarc** [comment]
@nano0tech Hi. New version [**1.3.0**](https://plugins.jetbrains.com/plugin/21335-ai-commits/versions/stable/436633) has been released. Can you check if you can maybe fetch the other models? Thanks.

**Comment by nano0tech** [comment]
This is perfect... there are a ton of options now.

I believe only the chat completion models are the most relevant here.

https://platform.openai.com/docs/models/model-endpoint-compatibility

```
/v1/chat/completions	gpt-4 and dated model releases, gpt-4-1106-preview, gpt-4-vision-preview, gpt-4-32k and dated model releases, gpt-3.5-turbo and dated model releases, gpt-3.5-turbo-16k and dated model releases, fine-tuned versions of gpt-3.5-turbo
```

Here's what I see now:

![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/4233e72f-1023-4fe3-beec-e95fb4b6358b)

![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/98cab7aa-af40-4bef-bbca-c777193156f3)

![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/6146176/5797bedf-7d4b-4b89-89a6-f207dec8f5c8)

... and so on.

All of the chat completion models are present! ✅
-------

Thanks again!
