### ISSUE TITLE
option to set custom timeout 

### ISSUE THREAD

**Issue by jakvb** [Blarc/ai-commits-intellij-plugin#118]
Thank you for great work on this plugin.
I connected plugin to local OpenAI - like server and generation of response takes sometime longer than currently set `socket-timeout:30000` ms.
Can you add field to customize this timeout?

Thanks!

**Comment by Blarc** [comment]
Added in version [v1.5.0](https://github.com/Blarc/ai-commits-intellij-plugin/releases/tag/v1.5.0). You can install it [manually](https://github.com/Blarc/ai-commits-intellij-plugin?tab=readme-ov-file#installation-from-zip) or wait for JetBrains to approve it and release it on the marketplace.
