### ISSUE TITLE
Diff "before" and "after" is swapped in "Edit Prompt" settings window 

### ISSUE THREAD

**Issue by umanamente** [Blarc/ai-commits-intellij-plugin#119]
I noticed that the diff in "Edit Prompt" window in plugin settings is generated as if "before" and "after" are swapped. 
It looks like it is just in "Edit Prompt" window, and not in the diffs that are sent to the AI model.

Version: 1.4.0

**Comment by Blarc** [comment]
I am not sure I understand correctly. The preview tries to show what is sent to the AI model, so you can write better prompt.

**Comment by umanamente** [comment]
> I am not sure I understand correctly. The preview tries to show what is sent to the AI model, so you can write better prompt.

Yes, and I see that in this preview "+" and "-" (added and removed lines) are swapped, meaning that it shows that I removed some lines, while I actually added them. 
So if I paste this "preview" prompt into ChatGPT, it generates "Removed this and that" instead of "Added ..."

**Comment by Blarc** [comment]
Thanks a lot for reporting the issue. I think I found the bug and it will be fixed in the next release. :pray:
