### ISSUE TITLE
Can't see AI Commits page in settings in 1.5.0

### ISSUE THREAD

**Issue by sudoskys** [Blarc/ai-commits-intellij-plugin#124]
- PyCharm2023.3 pro
- Arch Linux 
Settings > Tools > ?

**Comment by Blarc** [comment]
Can you please provide more information? Can you see the plugin in `Plugins > Installed` tab?

**Comment by sudoskys** [comment]
@Blarc Yes, i can

**Comment by sudoskys** [comment]
This may not be a problem with this project, but a translation error.

**Comment by sudoskys** [comment]
This may not be a problem with this project, but a translation error.

**Comment by yanzhaohaojie** [comment]
中文汉化包文件“zh.233.287\lib\zh.233.287\messages\MyBundle.properties”的内容为：
name=运行时性能测试插件

AICommits\lib\instrumented-ai-commits-intellij-plugin-1.6.0\messages\下有个文件“MyBundle.properties”。

上述两个文件重名，导致汉化版Idea中的AICommits显示异常。
