### ISSUE TITLE
Add support for partial commits of a changeset

### ISSUE THREAD

**Issue by whjvenyl** [Blarc/ai-commits-intellij-plugin#136]
Use the CommitDialogChangesBrowser as in https://github.com/carlrobertoh/CodeGPT/blob/f3357ff0a6f16be79b9a8be70de18cd6513541f2/src/main/java/ee/carlrobert/codegpt/actions/GenerateGitCommitMessageAction.java#L154

**Comment by Blarc** [comment]
I think I already do this with ` val includedChanges = commitWorkflowHandler.ui.getIncludedChanges()` in https://github.com/Blarc/ai-commits-intellij-plugin/blob/ff8f4ba5936c38737a4f7a3effe65978d2e61a7f/src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitAction.kt#L32C8-L32C76.

**Comment by whjvenyl** [comment]
Your implementation seems to include the whole gitt-diff instead of only the selected changes. Running the same backend and commit prompt, I had huge differences in the generated output. Yours seemed quite off (as if the whole gitt-diff was used for the input), the other one on point.

**Comment by Blarc** [comment]
Even more, if you deselect a single line in the commit dialog, it won't be added to the prompt:
![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/36704759/d12b7874-e157-4d65-89ac-7001a10cdfbf)
