### ISSUE TITLE
Can't generate commit's message in intellij

### ISSUE THREAD

**Issue by thangpn0207** [Blarc/ai-commits-intellij-plugin#143]
When i use AI commit, system throw error like this:
<img width="372" alt="Screenshot 2024-02-20 at 16 58 16" src="https://github.com/Blarc/ai-commits-intellij-plugin/assets/79156593/bfbf8cc0-20ed-439d-9c06-0fdf3cc9a5bb">
In spite of, I used my GPT token.

**Comment by Blarc** [comment]
Duplicated https://github.com/Blarc/ai-commits-intellij-plugin/issues/31.
