### ISSUE TITLE
If the Language Pack plugin is installed in IDEA, it could cause ai commits to become unusable.

### ISSUE THREAD

**Issue by LukcyOne** [Blarc/ai-commits-intellij-plugin#153]
plugin version: 1.6.0

If the Language Pack plugin is installed in IDEA, you will not be able to find the ai commits setting option in the settings. Even after uninstalling the Language Pack plugin, properly configuring ai commits, and reinstalling the Language Pack plugin, it still cannot be used normally.

**Comment by Blarc** [comment]
Hey. Thanks for reporting this. I'll try to reproduce this and see if I can fix it. This was [already reported once](https://github.com/Blarc/ai-commits-intellij-plugin/issues/124#issuecomment-1968422225) but was resolved as it seemed to be a bug in Language Pack Plugin.

**Comment by youchenga** [comment]
> Hey. Thanks for reporting this. I'll try to reproduce this and see if I can fix it. This was [already reported once](https://github.com/Blarc/ai-commits-intellij-plugin/issues/124#issuecomment-1968422225) but was resolved as it seemed to be a bug in Language Pack Plugin.

Oh indeed, this is a duplicate issue. Even the location of the error is identical.

**Comment by Blarc** [comment]
Thanks for reporting the issue to JetBrains. I'll just save the link to YouTrack here: https://youtrack.jetbrains.com/issue/IDEA-348712/The-settings-of-the-AI-commits-plugin-have-been-incorrectly-translated..
