### ISSUE TITLE
[Bug] Updated prompt selection unexpectedly reset after saving

### ISSUE THREAD

**Issue by chachako** [Blarc/ai-commits-intellij-plugin#156]
I have a custom prompt that I am using. When I modify and update it again, and then save the settings, I find that the prompt selection has reset to **`Basic`**.

**Comment by Blarc** [comment]
This was fixed and will be released in next version https://github.com/Blarc/ai-commits-intellij-plugin/commit/1d8b5e4760bae38fa202d01450e10a0f0aff5413.

**Comment by Blarc** [comment]
Are you using the latest version? This should've been fixed in 1.6.0. Same bug in previous issue: https://github.com/Blarc/ai-commits-intellij-plugin/issues/131.

**Comment by chachako** [comment]
I'm sure I'm using the latest version, as even the main branch has this issue

**Comment by Blarc** [comment]
Hey @chachako, is this still relevant? I can't reproduce. Thanks :pray: .

**Comment by chachako** [comment]
@Blarc Good job, no problems now!
