### ISSUE TITLE
exceeded your current quota

### ISSUE THREAD

**Issue by Abdurahman-hassan** [Blarc/ai-commits-intellij-plugin#158]
i got an error after generating an api key and try to generate a commit message:

You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

**Comment by Blarc** [comment]
Duplicated: https://github.com/Blarc/ai-commits-intellij-plugin/issues/31 https://github.com/Blarc/ai-commits-intellij-plugin/issues/93
