### ISSUE TITLE
Add feedback on the progress of the request

### ISSUE THREAD

**Issue by DylanDelobel** [Blarc/ai-commits-intellij-plugin#16]
This morning I suppose OpenIA resply slowly,

Without any feedback I click on the IA commit button again, still nothing I click a 3rd time
And now my commit message change like 3 time in a row qucikly

I would like some feedback where the request is and/or not be able to send the request while the first one is not done? 🙏

**Comment by Blarc** [comment]
Good suggestion :100: . Will look into it. Thanks.
