### ISSUE TITLE
Error occurred: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by CiaranMcHugh** [Blarc/ai-commits-intellij-plugin#168]
1. I get the following error using IntelliJ IDEA 2024.1 (Ultimate Edition).
2. Plugin configured with valid project api key from https://platform.openai.com/api-keys

`Error occurred: unable to find valid certification path to requested target`

![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/5495237/b5367eed-2504-4ea1-bbcd-9b030aee937d)

**Comment by MartinGiner9** [comment]
Same error there!
![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/100756709/18a08784-4182-4522-8564-9c0d79066073)
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
