### ISSUE TITLE
Replace token not working

### ISSUE THREAD

**Issue by CrazyBoy49z** [Blarc/ai-commits-intellij-plugin#17]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/3448603/230712859-60996291-5614-449f-b852-64e55dfabc07.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3448603/230712880-8bd65e62-81ba-45c5-89ec-81be45904a40.png">

Steps:
1. Delete previous token from OpenAi
2. Generate new token
3. Add new token to plugin and verify
4. Run generate commit

**Comment by Blarc** [comment]
I have released a new version **0.6.0** that contains a fix. You can wait for Jetbrains to aprove the new version and publish it on marketplace or install it manually by following [these](https://github.com/Blarc/ai-commits-intellij-plugin#installation-from-zip) steps.

Thank you for the report  :pray:
