### ISSUE TITLE
[BUG] Can't find the settings in IDEA 2024.1.2

### ISSUE THREAD

**Issue by YangAoLib** [Blarc/ai-commits-intellij-plugin#182]
# question

I can't find the corresponding settings item in Settings → Tools after installing the plugin in IDEA 2024.1.2.

# Steps to Reproduce

1. open IDEA 2024.1.2
2. Install this plug-in
3. open settings
4. Look for the AI Commits setting in Tool

# envirement

## system

版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎11/‎2
操作系统版本	22635.3646
体验	Windows Feature Experience Pack 1000.22700.1013.0

## ide version

IntelliJ IDEA 2024.1.2 (Ultimate Edition)
Build #IU-241.17011.79, built on May 22, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3990M
Cores: 32
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.chencn.yamlandprops (1.0.5)
  carbon-now-sh (1.3.0)
  com.intellij.zh (241.271)
  dev.meanmail.plugin.nginx-intellij-plugin-pro (2024.2)
  some.awesome (1.15)
  com.nasller.CodeGlancePro (1.8.5)
  de.netnexus.camelcaseplugin (3.0.12)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  com.jetbrains.space (241.17011.48)
  so.ray.linker (1.6)
  Key Promoter X (2024.1.0)
  com.robohorse.robopojogenerator (2.3.3)
  ink.organics.pojo2json (2.0.6)
  com.intellij.aqua (241.17011.127)
  GrepConsole (13.0.2-IJ2023.3)
  PlantUML integration (7.10.1-IJ2023.2)
  MyBatisLog (2024.4.1)
  JRebelPlugin (2024.2.1)
  jr-mp-ide-idea (0.0.6)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  pro.bashsupport (4.1.3.241)
  com.github.copilot (1.5.5.5632)
  io.github.kings1990.FastRequest (2024.1.5.1)
  SequenceDiagram (3.0.9)
  com.apifox.uploader (1.2.4)
  cn.cloud.auto.restful.tool (2024.5.12.819)
  com.xxxtai.coding.SmartInputSourceIntelliJ (6.0.4)
  org.sonarlint.idea (10.6.1.78652)
  zielu.gitworktree (1.0.4+231)
  com.github.blarc.ai-commits-intellij-plugin (1.6.0)
  zielu.gittoolbox (500.2.8+233)
  com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (3.3.2+2322)
  cn.yiiguxing.plugin.translate (3.6.1)
  org.freeone.javabean.tsinterface (0.0.12)
Kotlin: 241.17011.79-IJ

**Comment by Blarc** [comment]
Hey @YangAoLib ,

this is a bug with language pack: https://github.com/Blarc/ai-commits-intellij-plugin/issues/153.
