### ISSUE TITLE
[Feature Request] Support Gemini API

### ISSUE THREAD

**Issue by IRedDragonICY** [Blarc/ai-commits-intellij-plugin#196]
Support Gemini API ![image](https://www.gstatic.com/lamda/images/gemini_sparkle_red_4ed1cbfcbc6c9e84c31b987da73fc4168aec8445.svg) (from Vertex or Makersuite)╰(*°▽°*)╯

**Comment by Blarc** [comment]
Added in [v2.1.0](https://github.com/Blarc/ai-commits-intellij-plugin/releases/tag/v2.1.0).

**Comment by IRedDragonICY** [comment]
Thanks😁👍🏻

**Comment by Blarc** [comment]
@IRedDragonICY please report back any problems you might have, since I couldn't really test it, because I don't have a subscription. Thanks :pray: .

**Comment by IRedDragonICY** [comment]
Hello @Blarc,

I have reviewed the new update and noticed that it currently supports only the Vertex format and not the Google AI Studio (Makersuite) format.

There are currently three models:
- gemini-1.5-pro
- gemini-1.5-flash
- gemini-1.0-pro

Here is an example from Google AI Studio: (cURL)

```cURL
API_KEY="YOUR_API_KEY"

curl \
  -X POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${API_KEY} \
  -H 'Content-Type: application/json' \
  -d @<(echo '{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "INSERT_INPUT_HERE"
        }
      ]
    }
  ],
  "generationConfig": {
    "temperature": 1,
    "topK": 64,
    "topP": 0.95,
    "maxOutputTokens": 8192,
    "responseMimeType": "text/plain"
  },
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    }
  ]
}')
```

For Google AI Studio, we don't require Project ID and Location, only the Model and API key.

Thank you for your attention to this detail.

**Comment by Blarc** [comment]
Hey @IRedDragonICY,
it seems [langchain4j](https://docs.langchain4j.dev/) does not support this format?

**Comment by IRedDragonICY** [comment]
Unfortunately, it seems that Google AI Studio is not supported by langchain4j at this time, with only the Google Vertex format being compatible. As a temporary workaround, you might consider making HTTP requests manually for integration with Google AI Studio.

**Comment by Blarc** [comment]
> Unfortunately, it seems that Google AI Studio is not supported by langchain4j at this time, with only the Google Vertex format being compatible. As a temporary workaround, you might consider making HTTP requests manually for integration with Google AI Studio.

I would rather try to open an issue or PR to langchain4j and first add the integration there.

**Comment by MarJose123** [comment]
@IRedDragonICY you can use this and stage on vercel on your own, this is what i'm using since the plugin doesn't support yet Gemini.

https://github.com/PublicAffairs/openai-gemini

**Comment by IRedDragonICY** [comment]
> @IRedDragonICY you can use this and stage on vercel on your own, this is what i'm using since the plugin doesn't support yet Gemini.


@MarJose123, Thanks for the suggestion! I’ve been using a similar solution for now, which is this repository: [zhu327/gemini-openai-proxy](https://github.com/zhu327/gemini-openai-proxy). It's been working quite well as an interim measure until there's official support in the plugin.

**Comment by GenhaoLi** [comment]
> @IRedDragonICY you can use this and stage on vercel on your own, this is what i'm using since the plugin doesn't support yet Gemini.
> 
> [PublicAffairs/openai-gemini](https://github.com/PublicAffairs/openai-gemini)

Thanks a lot for the incredibly easy workaround!

Just wanna add a bit more info for anyone like me who doesn't have much experience with Vercel:
- In [PublicAffairs/openai-gemini](https://github.com/PublicAffairs/openai-gemini) README.md, just click the **`Deploy`** button under [**Deploy with Vercel**](https://github.com/PublicAffairs/openai-gemini#deploy-with-vercel), and follow all the instructions (login github, clone the repo, deploy the project, etc.). Then you will have a domain like `xxxxx.vercel.app`
- Append `v1` to the url and put it in field `Host` in plugin settings page `Edit LLM Client`, e.g. `Host` `https://xxxxx.vercel.app/v1`, paste your Gemini api key in field `Token`, and then click `Verify` and `Update`
