### ISSUE TITLE
New feature request: Allows user set network proxy

### ISSUE THREAD

**Issue by wangtao94** [Blarc/ai-commits-intellij-plugin#21]
# Description:

I'm using the `ai-commits-intellij-plugin` , but I cannot do so from mainland China due to internet restrictions. Therefore, I would like to request the addition of a new feature that allows users to set a network proxy in the plugin's settings, so that users in China can access the openai API.

# Expected behavior:

1. The plugin should allow users to set a network proxy in its settings.
Additional information:

We can't request openai in China.
Adding support for network proxies would greatly benefit users in China who want to use the ai-commits-intellij-plugin to access openai API.

**Comment by Blarc** [comment]
I have released a new version [**0.7.0**](https://github.com/Blarc/ai-commits-intellij-plugin/releases/tag/v0.7.0)  that contains this feature. You can wait for JetBrains to aprove the new version and publish it on marketplace or install it manually by following [these](https://github.com/Blarc/ai-commits-intellij-plugin#installation-from-zip) steps.

Thank you for the feature request :+1:
