### ISSUE TITLE
Per Project Default Prompt

### ISSUE THREAD

**Issue by mydnic** [Blarc/ai-commits-intellij-plugin#229]
Is it possible to have the plugin settings per project?

I have multiple prompts, some are better suited for specific projects or clients.

When I open another project I have to open the plugin settings to change the value of the "Prompt" select list, then save.
I have to do this for any project that might use a different prompt.

That would be true for the "Locale" settings.

it would be nice to define only once the right settings per project.

Is there a solution ?

Sorry if this is not the right place to ask.

**Comment by Blarc** [comment]
Hey @mydnic,

that seems very reasonable. I'll have to think about how to keep both options though.

**Comment by mydnic** [comment]
@Blarc thanks for the last update :) however I think there's a bug.
Changing the setting to use another locale / another prompt does not change anything, it's still using the "old" one I previously had.

So, before the update I had prompt X in my settings.
After the update, I changed the prompt to use Prompt Y, and selected "Project Specific"
Save and Apply
Even quit and restart phpstorm
Generate commits -> it's using the Prompt X, even though Prompt Y is selected

Maybe it's just me?

**Comment by Blarc** [comment]
Hopefully [this](https://github.com/Blarc/ai-commits-intellij-plugin/commit/bd7e60f0a07a6156e6d91d8dbe021825a1674ac1) fixes it. I'm sorry for the troubles...

**Comment by mydnic** [comment]
Looks like its working now ! thanks

**Comment by mydnic** [comment]
@Blarc it's me again :D 

I think there's still an issue

Every time I reopen a project, it seems that the Default Prompt resets to another choice.
The language however is saved correctly

Maybe it's my settings that were not saved correctly. Do you know how I could make sure the settings are "forced-saved" ?

**Comment by Blarc** [comment]
Hey @mydnic, sorry for such a late response. I can't reproduce what you are describing. The project specific LLM client, prompt and locale are saved in project settings, therefore you can see them in an xml file `AICommit.xml` inside of the `.idea` folder on the root of your project. 

This is how it looks for me:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="com.github.blarc.ai.commits.intellij.plugin.settings.ProjectSettings" activeLlmClientId="5bfbb5e1-88ff-45ea-80a7-9695573c34c9" isProjectSpecificLLMClient="true" isProjectSpecificPrompt="true">
    <option name="activePrompt">
      <Prompt>
        <option name="content" value="Test" />
        <option name="description" value="Test" />
        <option name="name" value="Test" />
      </Prompt>
    </option>
    <!-- Actually not sure why these two are here. I believe they are not be used. -->
    <option name="projectSpecificLLMClient" value="true" />
    <option name="projectSpecificPrompt" value="true" />
    <option name="locale" value="ig" />
  </component>
</project>
```

Maybe you can first check if the xml file contains the correct data?

**Comment by Blarc** [comment]
Huh nevermind... something wierd is indeed going on. After un-checking the checkbox, saving and checking again, the prompt is not saved. Will investigate and report back... :eyes:
