### ISSUE TITLE
Support amend commits

### ISSUE THREAD

**Issue by esafak** [Blarc/ai-commits-intellij-plugin#230]
You should be able to create summaries of amended commits, where only the summary changes. Instead it says the diff is empty.

**Comment by Blarc** [comment]
Hey @esafak, can you explain what do you mean by "where only the summary changes" ?

**Comment by esafak** [comment]
Suppose you make a commit, with the wrong message, and you want to regenerate it by using an amend. The plugin sees nothing has changed and does nothing.

**Comment by Blarc** [comment]
One workaround is to undo the commit and run the action again. However, I'll see if I can come up with something better...

**Comment by Blarc** [comment]
Hey @esafak,

this is not supported in the lates version [v2.4.0](https://plugins.jetbrains.com/plugin/21335-ai-commits).
