### ISSUE TITLE
Generated commit message is not correct

### ISSUE THREAD

**Issue by ErikBrabander** [Blarc/ai-commits-intellij-plugin#233]
The plugin used to work perfect. But now it does not generate messages from the diff so it seems. I have to write the message myself. The next time i try to generate a commit message the message looks like a rewrite of my last commit message and not about what i just changed in the code. 

Is any body else experiencing the same?

**Comment by Blarc** [comment]
Hey @ErikBrabander,

you can try to troubleshoot by checking the prompt preview when editing the prompt in settings. In the preview you can see what is sent to the LLM model.

**Comment by ErikBrabander** [comment]
Hi,

Thank you for your quick reply. Here is the preview:

`Write an insightful but concise Git commit message in a complete sentence in present tense for the following diff without prefacing it with anything, the response must be in the language English and must NOT be longer than 74 characters. The sent text will be the differences between files, where deleted lines are prefixed with a single minus sign and added lines are prefixed with a single plus sign.
Use this hint to improve the commit message: This is a hint.
Repository: /Users/erikbrabander/Projects/kerstpakketten-backoffice
Index: api/app/Http/Controllers/CustomerController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/app/Http/Controllers/CustomerController.php b/api/app/Http/Controllers/CustomerController.php
--- a/api/app/Http/Controllers/CustomerController.php	(revision 440da8ea0eca92f5e8399e3f32dfca3f0e05eb37)
+++ b/api/app/Http/Controllers/CustomerController.php	(date 1725444266524)
@@ -108,7 +108,10 @@
                 }
             } else {
                 // Check if customer already exists
-                $cust = Customer::where('email', $validatedData['email'])->first();
+                $cust = Customer::where('email', $validatedData['email'])
+                    ->where('active', '=', 1)
+                    ->where('guest', '=', 0)
+                    ->first();
             }
 
             $customerCreated = false;
`

The commit message that was generated was: "Add birth date to the PDF header in the CustomerController." As you can see in the diff... that is not what is changed ;-)

**Comment by Blarc** [comment]
I'm not sure if this is something I can help you with :grimacing:. This can depend a lot on which model you are sending your requests to and the configuration you are using (the temperature property for example). Also keep in mind that the plugin only sends the diff for the files that are **selected** in the commit dialog.

**Comment by ErikBrabander** [comment]
Hi, just found out through a colleague of mine, who also had the same issue, that when you delete the previous commit message from the commit message box and then click on the generate button the commits do work better.

**Comment by Blarc** [comment]
Would you mind sharing the prompt you use? You probably need to remove the hint variable `${hint}`.

**Comment by ErikBrabander** [comment]
sure, here it is:

Write an insightful but concise Git commit message in a complete sentence in present tense for the following diff without prefacing it with anything, the response must be in the language English and must NOT be longer than 74 characters. The sent text will be the differences between files, where deleted lines are prefixed with a single minus sign and added lines are prefixed with a single plus sign.
{Use this hint to improve the commit message: $hint}
{diff}

**Comment by ErikBrabander** [comment]
I tried your suggestion and removing ${hint} from the prompt seems to be working. Awesome!
Thanks so much for your help.
