### ISSUE TITLE
Issue with commit message generation for new files

### ISSUE THREAD

**Issue by vaened** [Blarc/ai-commits-intellij-plugin#244]
Description

I’ve observed that the Commit AI plugin works well for generating commit messages for existing tracked files but does not seem to generate messages for newly added files. I am unsure if this behavior is expected or if there might be an issue with the configuration.

Steps to Reproduce

1.	Create a new file in your project.
2.	Select the new file for commit.
3.	Invoke Commit AI to generate a commit message.

Expected Behavior

The plugin should generate a commit message for the newly added file, similar to how JetBrains AI handles both new and modified files.

Actual Behavior

The plugin does not generate a commit message for new files. When attempting to generate a message for a new file, an error message appears: “Git diff is empty.”

Additional Information

•	Commit AI Version: 2.3.1
•	PHPStorm Version: 2024.2.1

Could you please advise if there’s a specific setup required for handling new files, or if this is a known limitation of the plugin? Any guidance would be greatly appreciated.

Thank you!

**Comment by Blarc** [comment]
Huh, you are correct. This is not intended and will be fixed.

**Comment by Blarc** [comment]
There were some wierd shenanigans going on, hopefully [this](https://github.com/Blarc/ai-commits-intellij-plugin/commit/11898124161237123068eac146f1bede8dc50534) will fix it. Please report back if this is not resolved :pray: .

**Comment by vaened** [comment]
Hi, thank you for the quick fix!

I downloaded and installed the new build manually, but unfortunately, the issue still persists. When I attempt to generate a commit message for a new file, I continue to see the message: “Git diff is empty.”

Here’s what I did:
1.	Downloaded the artifact from the latest workflow.
2.	Installed the plugin manually in PHPStorm (version 2024.2.1).
3.	Tested with a new file, and the “Git diff is empty” message still appears.

Please let me know if there’s anything else I can try or if further information is needed to help debug this.

Thanks again

**Comment by Blarc** [comment]
Can you please check if the prompt preview, in the prompt edit dialog, shows the new file or not? Thanks :+1: .

**Comment by vaened** [comment]
In the message editing dialog I see that I am selecting 1 file. I have attached a screenshot showing what I see when I try to generate a confirmation message for a new file.

![Pasted Graphic](https://github.com/user-attachments/assets/f751ba29-128f-423d-91c4-16410632968d)

**Comment by Blarc** [comment]
Aha, the problem might be that the file is not added to the VCS. Try to right click on the file click `Add to VCS`.

**Comment by vaened** [comment]
Great news, that fixed the issue! It turns out the file needed to be added to VCS first. I was accustomed to JetBrains AI, where this step wasn’t necessary. I apologize for any inconvenience caused and appreciate your assistance. Thank you for your help!
