### ISSUE TITLE
[Feature Request]Add support for Huggingface TGI provider.

### ISSUE THREAD

**Issue by danny-su** [Blarc/ai-commits-intellij-plugin#256]
The URLs of the models look like the following:
 https://api-inference.huggingface.co/models/mistralai/Mistral-Nemo-Instruct-2407

**Comment by Blarc** [comment]
Hey, yeah I can add HuggingFace provider, since it's supported by langchain4j: https://docs.langchain4j.dev/integrations/language-models/hugging-face/.
