### ISSUE TITLE
Add support for GitHub Copilot to generate commit messages

### ISSUE THREAD

**Issue by hemeroc** [Blarc/ai-commits-intellij-plugin#282]
Could you please add support for GitHub Copilot to generate commit messages.

[langchain4j](https://github.com/langchain4j/langchain4j) should since the latest version support the GitHub model.

Thank you very much for the cool project.

**Comment by Blarc** [comment]
Hey @hemeroc,

thanks for opening the issue.

Support for GitHub models has been added with https://github.com/Blarc/ai-commits-intellij-plugin/commit/8e62ce91dd169068d0852ec28f5dfa07426efac2.
