### ISSUE TITLE
PhpStorm progress bar still loading even after the AI commit message is already generated

### ISSUE THREAD

**Issue by MarJose123** [Blarc/ai-commits-intellij-plugin#290]
The progress bar is still visible even if the commit message is already present, and even after it was committed to the repository, the progress bar for "Generating commit message" is still visible.

This was working fine around `v2.3.0`

Attached screen recording of the issue:

[Screen Recording 26-11-2024 at 14.04.webm](https://github.com/user-attachments/assets/804d17d8-38a4-4027-892f-5d07346eaf1c)

**Comment by Blarc** [comment]
Hey @MarJose123, I can't really repeat this. Is this something that happens on regular basis?

**Comment by MarJose123** [comment]
> Hey @MarJose123, I can't really repeat this. Is this something that happens on regular basis?

In my case, yes. I experienced this issue a while ago after I updated the plugin. I just ignored it the first time I noticed, as I do not have time to report the issue.

Is there a chance that this may be caused by the IDE itself?

**Comment by Blarc** [comment]
> > Hey @MarJose123, I can't really repeat this. Is this something that happens on regular basis?
> 
> In my case, yes. I experienced this issue a while ago after I updated the plugin. I just ignored it the first time I noticed, as I do not have time to report the issue.
> 
> Is there a chance that this may be caused by the IDE itself?

Not sure, but maybe you could first try to disable the nyan cat plugin and see if maybe that is causing the issue?

**Comment by MarJose123** [comment]
> Not sure, but maybe you could first try to disable the nyan cat plugin and see if maybe that is causing the issue?

After I uninstalled the Nyan Cat plugin, it was still not working; however, if the API returned a message of `Error: [429 RESOURCE_EXHAUSTED] Resource has been exhausted (e.g. check quota).` the progress bar would hide as expected.

I found the cause of the issue. It is in the `AI Commits` plugin setting. If `Streaming response` is ticked, then I think the plugin is still waiting for a response to stream or the connection is still open after, I guess.

**Comment by Blarc** [comment]
> After I uninstalled the Nyan Cat plugin, it was still not working; however, if the API returned a message of `Error: [429 RESOURCE_EXHAUSTED] Resource has been exhausted (e.g. check quota).` the progress bar would hide as expected.
> 
> I found the cause of the issue. It is in the `AI Commits` plugin setting. If `Streaming response` is ticked, then I think the plugin is still waiting for a response to stream or the connection is still open even after the response has been streamed by the reader.

Which LLM are you using?

**Comment by MarJose123** [comment]
Im using a Gimini but I I'm not using the available Gimini LLM in the setting. I'm using nodejs to connect to Gimini  API.

**Comment by Blarc** [comment]
The plugin will now stop the background process if the user commits the changes (https://github.com/Blarc/ai-commits-intellij-plugin/commit/7694a439a75e65d5e42a6981b3bf86ed917e5acf) and will show a stop icon while the process is running (https://github.com/Blarc/ai-commits-intellij-plugin/commit/36d38a82867cac15ab41f44f44c3b9e3f497aeb3).

This way you'll be able to know for sure, if the background process is still running and it's not just a bug in the UI. Please report back after the new version is released :pray: .

**Comment by MarJose123** [comment]
I'm closing this as the issue is resolved with the `v2.9.0` 🍻
