### ISSUE TITLE
How do I customize the num_ctx parameter?

### ISSUE THREAD

**Issue by igor-adzz** [Blarc/ai-commits-intellij-plugin#291]
Ollama supports various model customizations that are only available when passing a request in a JSON object. How can I access this request to, for example, increase the size of the context window?

![image](https://github.com/user-attachments/assets/1a0a4b32-0551-40a7-8aeb-76a9340aa53b)

**Comment by Blarc** [comment]
Hey @igor-adzz , this is currently not supported by the plugin, but I can add this. It would help if you could provide some documentation about this, otherwise I'll google it myself, thanks :pray: .

**Comment by igor-adzz** [comment]
@Blarc here: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-request-with-options

Thank you! Very cool product. I use it every day.

**Comment by Blarc** [comment]
@igor-adzz That's a lot of options. Do you think the plugin should support all of them or do you have any specific in mind?
