### ISSUE TITLE
allow to configure another openai compatible api url

### ISSUE THREAD

**Issue by cforce** [Blarc/ai-commits-intellij-plugin#35]
Auzure OpenAI is compatible and shall just work.
It's a more dedicated way of uzing private owned models

**Comment by Blarc** [comment]
I have released a new version [1.0.0](https://github.com/Blarc/ai-commits-intellij-plugin/releases/tag/v1.0.0) that contains a setting for OpenAI api host. You can wait for JetBrains to aprove the new version and publish it on marketplace or install it manually by following [these](https://github.com/Blarc/ai-commits-intellij-plugin#installation-from-zip) steps.

Hopefully this is enough to change the API to Azure OpenAI.

**Comment by cforce** [comment]
i am missing the "model name" configuration 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/393286/233616513-9d469675-9ce6-42da-8bd3-7969d7be6b7b.png">
