### ISSUE TITLE
Not compatible with the version of your running IDE (PhpStorm 2022.2.3)

### ISSUE THREAD

**Issue by 70to** [Blarc/ai-commits-intellij-plugin#41]
I get the following message and cannot install, is there a solution?

```
Not compatible with the version of your running IDE (PhpStorm 2022.2.3)
```

**Comment by Blarc** [comment]
The plugin is supported for IDE versions 2023.1+. If there is a good reason why you haven't upgraded your IDE to the latest version, I might look into supporting lower versions.

**Comment by 70to** [comment]
Thank you!!
