### ISSUE TITLE
Add cfg for OpenAi @Azure - deployment

### ISSUE THREAD

**Issue by cforce** [Blarc/ai-commits-intellij-plugin#42]
See https://github.com/Blarc/ai-commits-intellij-plugin/issues/35#issuecomment-1517634517

---
EDIT: Added original comment:
i am missing the "deployment name" configuration 
https://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaistable/deployments/create?tabs=HTTP
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#completions
<img width="524" alt="image" src="https://user-images.githubusercontent.com/393286/233616513-9d469675-9ce6-42da-8bd3-7969d7be6b7b.png">

**Comment by Blarc** [comment]
Can't you just hardcode the `deployment-id` parameter in the url? 
`https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/completions?api-version={api-version}`

**Comment by cforce** [comment]
i tried but it says "Error occurred: Illegal input"

**Comment by Blarc** [comment]
I do not do any string validation for token. When you click on `verify` I just make a request to `v1/models` endpoint and check if response's status is 200.

Is Azure OpenAI free? Because I wanted to try it out myself, but it says it's only for business? I doubt that OpenAI and Azure OpenAI have the same endpoints. I would be prepared to add a special client for Azure OpenAI, if I had access.

**Comment by huajia2005** [comment]
I use  [https://github.com/stulzq/azure-openai-proxy](url) to convert the API of azure, and there is no problem in using it after conversion.Hope to be able to help you.

> i tried but it says "Error occurred: Illegal input" <img alt="image" width="795" src="https://user-images.githubusercontent.com/393286/235269759-87dc8085-c9a1-4fa1-9670-50bd79c115e7.png">
> 
> Possibly your do some "sk*" validation for the token? .. but azure token does not fit that expectation

I use  [https://github.com/stulzq/azure-openai-proxy](url) to convert the API of azure, and there is no problem in using it after conversion.Hope to be able to help you.
