### ISSUE TITLE
Add {branch} variable for prompt customisation

### ISSUE THREAD

**Issue by Blarc** [Blarc/ai-commits-intellij-plugin#43]
Add {branch} variable that resolves to current branch for prompt customisation

**Comment by Blarc** [comment]
Which branch should the plugin use, if you have multiple repositories open in one project?

**Comment by Blarc** [comment]
We could figure out branch for each file and then use the one that is the most common (that appears the most times).

**Comment by chupaSV** [comment]
Yes, this would be great.

**Comment by Blarc** [comment]
I have released a new version [1.1.0](https://github.com/Blarc/ai-commits-intellij-plugin/releases/tag/v1.1.0) that contains this feature. You can wait for JetBrains to aprove the new version and publish it on marketplace or install it manually by following [these](https://github.com/Blarc/ai-commits-intellij-plugin#installation-from-zip) steps.

Thank you for the feature request :pray:
