### ISSUE TITLE
why i couldn't use this plugin in Pycharm?

### ISSUE THREAD

**Issue by guaguaguaxia** [Blarc/ai-commits-intellij-plugin#55]
why i couldn't use this plugin in Pycharm?

**Comment by Blarc** [comment]
Hi,
can you give a bit more information? You can't install the plugin or the plugin throws an error?

**Comment by guaguaguaxia** [comment]
i can't search the plugin in pycharm marketplace,but it work in my IDEA

**Comment by guaguaguaxia** [comment]
![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/18466048/eb01ad00-bacc-478a-9968-ad7fa6efb77f)

**Comment by guaguaguaxia** [comment]
IDEA:IntelliJ IDEA 2023.1.2 (Ultimate Edition)
PyCharm:IntelliJ IDEA 2023.1.2 (Ultimate Edition)

**Comment by Blarc** [comment]
@guaguaguaxia I am using
```
PyCharm 2022.3.2 (Professional Edition)
Build #PY-231.9011.38, built on May 16, 2023
```
and I can see it in the marketplace:
![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/36704759/c6b4a1d9-4be0-4a74-a709-654b868548f1)

**Comment by guaguaguaxia** [comment]
![image](https://github.com/Blarc/ai-commits-intellij-plugin/assets/18466048/b28f3bfc-6dd8-4189-b128-d9ab047ae8ca)
i open the plugin website and it hint that

**Comment by Blarc** [comment]
Can you try to update PyCharm to latest version?

**Comment by guaguaguaxia** [comment]
ok,thanks
