### ISSUE TITLE
Models other than gpt-3.6 turbo do not work

### ISSUE THREAD

**Issue by rabayliss** [Blarc/ai-commits-intellij-plugin#64]
Bug description

Toggling the model for gpt-4, or 3, or any variant thereof in PyCharm gives the error:
"the model <> does not exist"

aicommits version

2.2.1

Environment

Windows 10 2023.1.2
Pycharm: PC-231.9011.38
Version 2023.1.2 
PyCharm 2023.1.2 (Community Edition)
Build #PC-231.9011.38, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
    ide.balloon.shadow.size=0

**Comment by Blarc** [comment]
Any chance you could check if the issue is still relevant? I believe the new version [1.3.0](https://plugins.jetbrains.com/plugin/21335-ai-commits/versions/stable/436633) should resolve this.
